// 客户档案Mock数据 - 与客户方案模块保持一致

import type { BusinessHistory, ContactPerson, CustomerProfile, OrganizationNode } from './types';
import { BusinessType, CustomerLevel, CustomerStatus, Gender } from './types';

// Mock客户列表数据（与客户方案模块的客户数据保持一致）
export const mockCustomerList: CustomerProfile[] = [
  {
    id: 1,
    customerCode: 'CUS-20240615-001',
    customerName: 'XX科技有限公司',
    customerShortName: 'XX科技',
    creditCode: '91110000MA01234567',
    registeredCapital: '5000万元',
    industry: '智能制造',
    region: '北京',
    level: CustomerLevel.Key,
    status: CustomerStatus.Cooperating,
    establishDate: '2015-03-15',
    legalRepresentative: '张某某',
    website: 'www.xxtech.com',
    responsiblePerson: '张三',
    address: '北京市海淀区中关村软件园XX号楼',
    tags: ['智能制造', '工业互联网', '国企客户', '重点关注'],
    introduction: 'XX科技是一家专注于智能制造领域的高新技术企业，主要从事工业自动化、智能制造系统集成等业务。',
    createByName: '张三',
    createTime: '2024-06-15 10:30:00',
    updateByName: '张三',
    updateTime: '2024-11-05 14:20:00',
  },
  {
    id: 2,
    customerCode: 'CUS-20240720-001',
    customerName: 'YY制造集团',
    customerShortName: 'YY集团',
    creditCode: '91310000MA02345678',
    registeredCapital: '10000万元',
    industry: '制造业',
    region: '上海',
    level: CustomerLevel.Key,
    status: CustomerStatus.Cooperating,
    establishDate: '2010-05-20',
    legalRepresentative: '李某某',
    website: 'www.yygroup.com',
    responsiblePerson: '李四',
    address: '上海市浦东新区张江高科技园区XX路XX号',
    tags: ['大型企业', 'MES系统', '长期合作'],
    introduction: 'YY制造集团是一家综合性制造企业，业务涵盖机械制造、电子产品等多个领域。',
    createByName: '李四',
    createTime: '2024-07-20 09:15:00',
    updateByName: '李四',
    updateTime: '2024-11-06 16:30:00',
  },
  {
    id: 3,
    customerCode: 'CUS-20240528-001',
    customerName: 'ZZ集团有限公司',
    customerShortName: 'ZZ集团',
    creditCode: '91440000MA03456789',
    registeredCapital: '20000万元',
    industry: '智能制造',
    region: '广州',
    level: CustomerLevel.Key,
    status: CustomerStatus.Cooperating,
    establishDate: '2008-08-10',
    legalRepresentative: '王某某',
    website: 'www.zzgroup.com',
    responsiblePerson: '王五',
    address: '广州市天河区珠江新城XX大厦',
    tags: ['物联网', '大数据', '上市公司'],
    introduction: 'ZZ集团是一家上市公司，专注于工业物联网平台建设和智能制造解决方案。',
    createByName: '王五',
    createTime: '2024-05-28 14:00:00',
    updateByName: '王五',
    updateTime: '2024-11-03 10:45:00',
  },
  {
    id: 4,
    customerCode: 'CUS-20240703-001',
    customerName: 'AA汽车配件',
    customerShortName: 'AA配件',
    creditCode: '91440000MA04567890',
    registeredCapital: '3000万元',
    industry: '汽车制造',
    region: '深圳',
    level: CustomerLevel.Normal,
    status: CustomerStatus.Intention,
    establishDate: '2018-03-25',
    legalRepresentative: '赵某某',
    website: 'www.aaparts.com',
    responsiblePerson: '赵六',
    address: '深圳市宝安区XX工业园',
    tags: ['汽车配件', '数字化转型'],
    introduction: 'AA汽车配件专业从事汽车零部件生产，正在进行数字化车间改造。',
    createByName: '赵六',
    createTime: '2024-07-03 11:20:00',
    updateByName: '赵六',
    updateTime: '2024-11-04 15:10:00',
  },
  {
    id: 5,
    customerCode: 'CUS-20240630-001',
    customerName: 'BB电子科技',
    customerShortName: 'BB科技',
    creditCode: '91330000MA05678901',
    registeredCapital: '8000万元',
    industry: '电子制造',
    region: '杭州',
    level: CustomerLevel.Normal,
    status: CustomerStatus.Cooperating,
    establishDate: '2012-06-15',
    legalRepresentative: '孙某某',
    website: 'www.bbtech.com',
    responsiblePerson: '孙七',
    address: '杭州市滨江区高新技术开发区XX路',
    tags: ['电子制造', 'ERP', 'MES'],
    introduction: 'BB电子科技从事电子产品研发和制造，已实施ERP和MES系统。',
    createByName: '李四',
    createTime: '2024-06-30 09:00:00',
    updateByName: '李四',
    updateTime: '2024-11-02 11:25:00',
  },
  {
    id: 6,
    customerCode: 'CUS-20240704-001',
    customerName: 'CC重工机械',
    customerShortName: 'CC重工',
    creditCode: '91320000MA06789012',
    registeredCapital: '15000万元',
    industry: '机械制造',
    region: '南京',
    level: CustomerLevel.Key,
    status: CustomerStatus.Cooperating,
    establishDate: '2005-11-20',
    legalRepresentative: '周某某',
    website: 'www.ccheavy.com',
    responsiblePerson: '周八',
    address: '南京市江宁区XX工业园',
    tags: ['重工机械', '设备维护', 'AI应用'],
    introduction: 'CC重工机械是大型机械制造企业，正在部署AI设备预测性维护系统。',
    createByName: '周八',
    createTime: '2024-07-04 13:30:00',
    updateByName: '周八',
    updateTime: '2024-11-05 09:15:00',
  },
  {
    id: 7,
    customerCode: 'CUS-20240625-001',
    customerName: 'DD化工集团',
    customerShortName: 'DD化工',
    creditCode: '91370000MA07890123',
    registeredCapital: '25000万元',
    industry: '化工',
    region: '济南',
    level: CustomerLevel.Key,
    status: CustomerStatus.Cooperating,
    establishDate: '2000-01-10',
    legalRepresentative: '吴某某',
    website: 'www.ddchem.com',
    responsiblePerson: '吴九',
    address: '济南市高新区XX化工园',
    tags: ['化工', '能源管理', '安全生产'],
    introduction: 'DD化工集团是国内知名化工企业，重视生产安全和能源管理。',
    createByName: '吴九',
    createTime: '2024-06-25 10:45:00',
    updateByName: '吴九',
    updateTime: '2024-10-31 14:50:00',
  },
  {
    id: 8,
    customerCode: 'CUS-20241005-001',
    customerName: 'EE食品有限公司',
    customerShortName: 'EE食品',
    creditCode: '91330000MA08901234',
    registeredCapital: '6000万元',
    industry: '食品制造',
    region: '杭州',
    level: CustomerLevel.Normal,
    status: CustomerStatus.Intention,
    establishDate: '2016-09-01',
    legalRepresentative: '郑某某',
    website: 'www.eefood.com',
    responsiblePerson: '张三',
    address: '杭州市余杭区XX食品工业园',
    tags: ['食品安全', '质量追溯'],
    introduction: 'EE食品公司专注食品生产，需要建设产品质量全流程追溯系统。',
    createByName: '张三',
    createTime: '2024-10-05 15:20:00',
    updateByName: '张三',
    updateTime: '2024-11-06 10:30:00',
  },
  {
    id: 9,
    customerCode: 'CUS-20240627-001',
    customerName: 'FF物流科技',
    customerShortName: 'FF物流',
    creditCode: '91440000MA09012345',
    registeredCapital: '12000万元',
    industry: '物流',
    region: '深圳',
    level: CustomerLevel.Key,
    status: CustomerStatus.Cooperating,
    establishDate: '2014-04-15',
    legalRepresentative: '钱某某',
    website: 'www.fflogistics.com',
    responsiblePerson: '钱十',
    address: '深圳市南山区XX物流园',
    tags: ['供应链', '物流信息化', '智能仓储'],
    introduction: 'FF物流科技提供现代化物流服务，正在建设供应链协同管理平台。',
    createByName: '钱十',
    createTime: '2024-06-27 11:00:00',
    updateByName: '钱十',
    updateTime: '2024-11-01 16:40:00',
  },
  {
    id: 10,
    customerCode: 'CUS-20241006-001',
    customerName: 'GG贸易公司',
    customerShortName: 'GG贸易',
    creditCode: '91310000MA10123456',
    registeredCapital: '4000万元',
    industry: '商贸',
    region: '上海',
    level: CustomerLevel.Normal,
    status: CustomerStatus.Cooperating,
    establishDate: '2019-07-20',
    legalRepresentative: '孙某某',
    website: 'www.ggtrade.com',
    responsiblePerson: '李四',
    address: '上海市虹口区XX商务大厦',
    tags: ['贸易', 'WMS系统'],
    introduction: 'GG贸易公司从事进出口贸易，需要智能仓储WMS系统提升效率。',
    createByName: '李四',
    createTime: '2024-10-06 08:50:00',
    updateByName: '李四',
    updateTime: '2024-11-06 14:15:00',
  },
  {
    id: 11,
    customerCode: 'CUS-20240629-001',
    customerName: 'HH精密制造',
    customerShortName: 'HH精密',
    creditCode: '91320000MA11234567',
    registeredCapital: '7000万元',
    industry: '精密制造',
    region: '苏州',
    level: CustomerLevel.Normal,
    status: CustomerStatus.Potential,
    establishDate: '2017-02-28',
    legalRepresentative: '冯某某',
    website: 'www.hhprecision.com',
    responsiblePerson: '冯十一',
    address: '苏州工业园区XX路',
    tags: ['精密制造', '数据采集'],
    introduction: 'HH精密制造从事精密零部件加工，需要生产数据采集分析平台。',
    createByName: '冯十一',
    createTime: '2024-06-29 16:10:00',
    updateByName: '冯十一',
    updateTime: '2024-11-05 11:20:00',
  },
  {
    id: 12,
    customerCode: 'CUS-20240631-001',
    customerName: 'II智能装备',
    customerShortName: 'II装备',
    creditCode: '91440000MA12345678',
    registeredCapital: '18000万元',
    industry: '智能制造',
    region: '深圳',
    level: CustomerLevel.Key,
    status: CustomerStatus.Cooperating,
    establishDate: '2011-09-10',
    legalRepresentative: '陈某某',
    website: 'www.iiequip.com',
    responsiblePerson: '陈十二',
    address: '深圳市龙华区XX智能装备产业园',
    tags: ['智能装备', 'AGV', '自动化'],
    introduction: 'II智能装备专业从事智能装备研发制造，已部署AGV智能搬运系统。',
    createByName: '陈十二',
    createTime: '2024-06-31 09:40:00',
    updateByName: '陈十二',
    updateTime: '2024-11-04 13:55:00',
  },
  {
    id: 13,
    customerCode: 'CUS-20241007-001',
    customerName: 'JJ钢铁集团',
    customerShortName: 'JJ钢铁',
    creditCode: '91130000MA13456789',
    registeredCapital: '50000万元',
    industry: '钢铁',
    region: '天津',
    level: CustomerLevel.Key,
    status: CustomerStatus.Intention,
    establishDate: '1998-05-15',
    legalRepresentative: '褚某某',
    website: 'www.jjsteel.com',
    responsiblePerson: '张三',
    address: '天津市滨海新区XX钢铁园',
    tags: ['钢铁', '设备健康', '大型国企'],
    introduction: 'JJ钢铁集团是大型钢铁企业，关注设备健康状态监测与管理。',
    createByName: '张三',
    createTime: '2024-10-07 10:30:00',
    updateByName: '张三',
    updateTime: '2024-11-07 15:45:00',
  },
  {
    id: 14,
    customerCode: 'CUS-20240626-001',
    customerName: 'KK光电科技',
    customerShortName: 'KK光电',
    creditCode: '91350000MA14567890',
    registeredCapital: '9000万元',
    industry: '光电',
    region: '福州',
    level: CustomerLevel.Normal,
    status: CustomerStatus.Lost,
    establishDate: '2013-10-20',
    legalRepresentative: '卫某某',
    website: 'www.kkoptics.com',
    responsiblePerson: '卫十三',
    address: '福州市马尾区XX光电产业园',
    tags: ['光电', '可视化监控'],
    introduction: 'KK光电科技从事光电产品研发，曾咨询产线可视化监控系统。',
    createByName: '卫十三',
    createTime: '2024-06-26 14:20:00',
    updateByName: '卫十三',
    updateTime: '2024-11-01 09:30:00',
  },
  {
    id: 15,
    customerCode: 'CUS-20241008-001',
    customerName: 'LL纺织集团',
    customerShortName: 'LL纺织',
    creditCode: '91330000MA15678901',
    registeredCapital: '11000万元',
    industry: '纺织',
    region: '杭州',
    level: CustomerLevel.Normal,
    status: CustomerStatus.Cooperating,
    establishDate: '2009-03-08',
    legalRepresentative: '蒋某某',
    website: 'www.lltextile.com',
    responsiblePerson: '蒋十四',
    address: '杭州市萧山区XX纺织工业园',
    tags: ['纺织', '智能排产', '优化算法'],
    introduction: 'LL纺织集团是区域龙头纺织企业，正在实施智能排产调度系统。',
    createByName: '蒋十四',
    createTime: '2024-10-08 09:15:00',
    updateByName: '蒋十四',
    updateTime: '2024-11-08 11:40:00',
  },
];

// 根据客户ID获取客户详情
export function getCustomerById(id: number): CustomerProfile | undefined {
  return mockCustomerList.find(c => c.id === id);
}

// 根据客户名称获取客户
export function getCustomerByName(name: string): CustomerProfile | undefined {
  return mockCustomerList.find(c => c.customerName === name);
}

// 获取客户的组织架构数据（示例）
export function getCustomerOrganization(customerId: number): OrganizationNode[] {
  // 这里返回示例数据，实际应该根据customerId返回对应数据
  return [
    {
      id: 1,
      key: '1',
      title: 'XX科技有限公司',
      departmentName: 'XX科技有限公司',
      children: [
        {
          id: 2,
          key: '1-1',
          title: '总经办',
          departmentName: '总经办',
          parentId: 1,
          responsiblePerson: '张经理',
          phone: '010-12345678',
          function: '公司综合管理、行政事务',
        },
        {
          id: 3,
          key: '1-2',
          title: '市场部',
          departmentName: '市场部',
          parentId: 1,
          children: [
            { id: 4, key: '1-2-1', title: '销售一部', departmentName: '销售一部', parentId: 3 },
            { id: 5, key: '1-2-2', title: '销售二部', departmentName: '销售二部', parentId: 3 },
          ],
        },
        {
          id: 6,
          key: '1-3',
          title: '技术部',
          departmentName: '技术部',
          parentId: 1,
          children: [
            { id: 7, key: '1-3-1', title: '研发组', departmentName: '研发组', parentId: 6 },
            { id: 8, key: '1-3-2', title: '测试组', departmentName: '测试组', parentId: 6 },
          ],
        },
        { id: 9, key: '1-4', title: '财务部', departmentName: '财务部', parentId: 1 },
      ],
    },
  ];
}

// 获取客户的联系人列表
export function getCustomerContacts(customerId: number): ContactPerson[] {
  const contactsMap: Record<number, ContactPerson[]> = {
    1: [
      {
        id: 1,
        customerId: 1,
        name: '张经理',
        gender: Gender.Male,
        position: '总经理',
        departmentId: 2,
        departmentName: '总经办',
        mobile: '13800138000',
        email: 'zhang@xxtech.com',
        telephone: '010-12345678',
        isPrimary: true,
        createTime: '2024-06-15 10:30:00',
      },
      {
        id: 2,
        customerId: 1,
        name: '李部长',
        gender: Gender.Male,
        position: '市场部长',
        departmentId: 3,
        departmentName: '市场部',
        mobile: '13800138001',
        email: 'li@xxtech.com',
        isPrimary: false,
        createTime: '2024-06-16 14:20:00',
      },
      {
        id: 3,
        customerId: 1,
        name: '王主管',
        gender: Gender.Female,
        position: '销售主管',
        departmentId: 4,
        departmentName: '销售一部',
        mobile: '13800138002',
        isPrimary: false,
        createTime: '2024-06-17 09:15:00',
      },
    ],
  };
  
  return contactsMap[customerId] || [];
}

// 获取客户的业务历史
export function getCustomerBusinessHistory(customerId: number): BusinessHistory[] {
  const historyMap: Record<number, BusinessHistory[]> = {
    1: [
      {
        id: 1,
        customerId: 1,
        businessType: BusinessType.Project,
        businessId: 1,
        businessCode: 'PRJ-2024-001',
        businessName: 'XX科技智慧工厂项目',
        businessAmount: 2000000,
        businessStatus: '实施中',
        businessTime: '2024-11-05 09:00:00',
        operator: '张三',
      },
      {
        id: 2,
        customerId: 1,
        businessType: BusinessType.Contract,
        businessId: 1,
        businessCode: 'HT-2024-001',
        businessName: '销售合同',
        businessAmount: 2000000,
        businessStatus: '已签订',
        businessTime: '2024-10-15 14:30:00',
        operator: '张三',
      },
      {
        id: 3,
        customerId: 1,
        businessType: BusinessType.Solution,
        businessId: 1,
        businessCode: 'CS-20241101-001',
        businessName: '智慧工厂整体解决方案',
        businessAmount: 2000000,
        businessStatus: '已发布',
        businessTime: '2024-09-20 10:15:00',
        operator: '张三',
      },
      {
        id: 4,
        customerId: 1,
        businessType: BusinessType.Opportunity,
        businessId: 1,
        businessCode: 'OPP-2024-001',
        businessName: 'XX科技智慧工厂需求',
        businessAmount: 2000000,
        businessStatus: '方案阶段',
        businessTime: '2024-08-10 15:00:00',
        operator: '张三',
      },
      {
        id: 5,
        customerId: 1,
        businessType: BusinessType.Opportunity,
        businessId: 1,
        businessCode: 'OPP-2024-001',
        businessName: 'XX科技智慧工厂需求',
        businessAmount: 2000000,
        businessStatus: '商机创建',
        businessTime: '2024-07-05 11:20:00',
        operator: '张三',
        remark: '客户来源：客户主动咨询',
      },
      {
        id: 6,
        customerId: 1,
        businessType: BusinessType.Created,
        businessName: '客户档案创建',
        businessTime: '2024-06-15 10:30:00',
        operator: '张三',
      },
    ],
  };
  
  return historyMap[customerId] || [];
}

// 客户统计数据映射
export function getCustomerStatistics(customerId: number) {
  const statsMap: Record<number, any> = {
    1: {
      opportunityCount: 5,
      solutionCount: 3,
      contractCount: 2,
      projectCount: 1,
      totalAmount: 2000000,
      paidAmount: 1500000,
      paymentRate: 75,
    },
  };
  
  return statsMap[customerId] || {
    opportunityCount: 0,
    solutionCount: 0,
    contractCount: 0,
    projectCount: 0,
    totalAmount: 0,
    paidAmount: 0,
    paymentRate: 0,
  };
}

